backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: product
    label: Producto
    folder: content/products
    create: true
    fields:
      - { name: title, label: Title }
      - { name: route, label: Ruta }
      - label: "Tamaños"
        name: "sizes"
        widget: "list"
        fields:
          - { label: "Tamaño", name: size, widget: string }
          - { label: "Precio", name: price, widget: number }
          - { label: "Imagen", name: image, widget: image }
      - label: "Colores"
        name: "colors"
        widget: "list"
        fields: 
          - { label: "Nombre", name: name, widget: string }
  - name: fragance
    label: Fragancia
    folder: content/fragances
    create: true
    fields: 
      - { name: title, label: Nombre }
      - { name: label, label: "Etiqueta a mostrar" }